# Generated by Django 3.1 on 2020-09-08 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldofStudy',
            fields=[
                ('id', models.UUIDField(default='41de5e459259490', editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.UUIDField(default='41de5e459259490', editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default='41de5e459259490', editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('isverified', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, max_length=5000, null=True)),
                ('shirt_size', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('T', 'Transgender'), ('P', 'Prefer Not To Say'), ('N', 'Non Binary,Gender Queer or gender non-confirming')], max_length=1)),
                ('no_formal_education', models.BooleanField(default=False)),
                ('degree_type', models.CharField(choices=[('Associate', 'Associate'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('High School', 'High School')], max_length=12)),
                ('grad_year', models.DateTimeField()),
                ('resume', models.FileField(upload_to=users.models.Profile.user_directory_path)),
                ('work_status', models.BooleanField(default=False)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('address', models.CharField(max_length=300)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.fieldofstudy')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.institute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default='41de5e459259490', editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default='41de5e459259490', editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('employer', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default='41de5e459259490', editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
