# Generated by Django 3.1 on 2020-09-08 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb21a520-438c-4e22-a734-eb814d79368d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institute',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb21a520-438c-4e22-a734-eb814d79368d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb21a520-438c-4e22-a734-eb814d79368d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb21a520-438c-4e22-a734-eb814d79368d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb21a520-438c-4e22-a734-eb814d79368d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb21a520-438c-4e22-a734-eb814d79368d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
