# Generated by Django 3.1 on 2020-09-09 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200908_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('T', 'Transgender'), ('P', 'Prefer Not To Say'), ('N', 'Non Binary,Gender Queer or gender non-confirming')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2959c8ce-54f1-441f-8b83-0dc752e45773'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institute',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2959c8ce-54f1-441f-8b83-0dc752e45773'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2959c8ce-54f1-441f-8b83-0dc752e45773'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2959c8ce-54f1-441f-8b83-0dc752e45773'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shirt_size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X Large'), ('XXL', 'XX Large'), ('XXXL', 'XXX Large')], max_length=4),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2959c8ce-54f1-441f-8b83-0dc752e45773'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2959c8ce-54f1-441f-8b83-0dc752e45773'), editable=False, primary_key=True, serialize=False),
        ),
    ]
