# Generated by Django 3.1 on 2020-09-09 15:25

from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200909_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd025513-0fa6-4242-94c7-a3f848c748a4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institute',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd025513-0fa6-4242-94c7-a3f848c748a4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd025513-0fa6-4242-94c7-a3f848c748a4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('Associate', 'Associate'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('High School', 'High School')], max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='field_of_study',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.fieldofstudy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grad_year',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd025513-0fa6-4242-94c7-a3f848c748a4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.institute'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, upload_to=users.models.Profile.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd025513-0fa6-4242-94c7-a3f848c748a4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd025513-0fa6-4242-94c7-a3f848c748a4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
