# Generated by Django 3.1 on 2020-09-09 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200909_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90f3e1fb-0a94-4725-be27-72b12d73825b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institute',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90f3e1fb-0a94-4725-be27-72b12d73825b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90f3e1fb-0a94-4725-be27-72b12d73825b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grad_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90f3e1fb-0a94-4725-be27-72b12d73825b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90f3e1fb-0a94-4725-be27-72b12d73825b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90f3e1fb-0a94-4725-be27-72b12d73825b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
