# Generated by Django 3.1 on 2020-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200910_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='setup',
            field=models.BooleanField(default=False),
        ),
    ]
