# Generated by Django 3.1 on 2020-09-25 15:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_otp',
            field=models.PositiveBigIntegerField(default=users.models.random_no),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_otp',
            field=models.PositiveBigIntegerField(default=users.models.random_no),
        ),
    ]
