# Generated by Django 3.1 on 2020-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200925_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isverified',
            new_name='mail_is_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
