# Generated by Django 3.1 on 2020-09-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
