# Generated by Django 3.1 on 2020-10-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200928_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grad_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(blank=True, to='users.Skill'),
        ),
    ]
