# Generated by Django 3.1 on 2020-10-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20201008_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='affiliation_no',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='date_opened',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='distric',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='off_ph_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='ph_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='pincode',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_exp_adm',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_exp_teach',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_qual',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='res_ph_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='society_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='year_found',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
