# Generated by Django 3.1 on 2020-10-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201012_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='distric',
            new_name='district',
        ),
    ]
