# Generated by Django 3.1 on 2020-10-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20201015_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='url',
            new_name='link',
        ),
    ]
