from django.db import models
from django.contrib.auth.models import User
from users.models import BaseClass
import random


def invite_code():
    code_chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    code = ''
    for i in range(0, 8):
        slice_start = random.randint(0, len(code_chars) - 1)
        code += code_chars[slice_start: slice_start + 1]
    return code


class Invite(BaseClass):
    '''
        These are invite codes are those which are generated by the user themselves 
    '''
    name = models.CharField(max_length=100, null=True, blank=True,)
    code = models.CharField(max_length=8, default=invite_code, unique=True, )
    user = models.OneToOneField(
        User, related_name='invite', on_delete=models.SET_NULL, null=True, blank=True)

    usedby_user = models.ManyToManyField(
        User, related_name='inviteused', blank=True)

    def usedby_count(self):
        self.usedby_user.all().count()

    def __str__(self):
        if self.user:
            return f'{self.user.username} Code '
        else:
            return f'{self.name} Campaign'
