# Generated by Django 3.1 on 2020-09-11 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('is_online', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=True)),
                ('official', models.BooleanField(default=False)),
                ('image', models.ImageField(default='event_logo/default.jpg', upload_to='event_logo')),
                ('cover_image', models.ImageField(default='event_cover/default.jpg', upload_to='event_cover')),
                ('address', models.CharField(max_length=300)),
                ('longitute', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('latitute', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('women_only', models.BooleanField(default=False)),
                ('approx_particpants', models.PositiveIntegerField()),
                ('team_size', models.SmallIntegerField()),
                ('team_min', models.SmallIntegerField()),
                ('winner_announced', models.BooleanField(default=False)),
                ('rsvp_email_sent_at', models.DateTimeField(blank=True)),
                ('reminder_email_sent_at', models.DateTimeField(blank=True)),
                ('feedback_reminder_sent_at', models.DateTimeField(blank=True)),
                ('not_accepeted_message', models.TextField()),
                ('waitlist_message', models.TextField()),
                ('accepted_message', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('medium', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('coc', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('priority', models.SmallIntegerField()),
                ('size', models.SmallIntegerField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.sponsortype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrizeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('priority', models.SmallIntegerField()),
                ('size', models.SmallIntegerField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.prizetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('only_speaker', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('detail', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(default='judge_profile/default.jpg', upload_to='judge_profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comp.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='organiser_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
