# Generated by Django 3.1 on 2020-09-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='accepted_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='feedback_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitute',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitute',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='not_accepeted_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='reminder_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rsvp_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='waitlist_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='judge',
            name='detail',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='detail',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='sponsortype',
            name='size',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
