# Generated by Django 3.1 on 2020-09-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_auto_20200911_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='approx_particpants',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='team_min',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='team_size',
            field=models.SmallIntegerField(default=4),
        ),
    ]
