# Generated by Django 3.1 on 2020-09-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0003_auto_20200911_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
