# Generated by Django 3.1 on 2020-09-14 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comp', '0004_auto_20200911_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_team_comp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prize',
            name='awarded_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('important', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('roll_name', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=True)),
                ('overview', models.BooleanField(default=False)),
                ('review', models.BooleanField(default=False)),
                ('volunteer', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('feedback', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('required', models.BooleanField(default=True)),
                ('types', models.CharField(choices=[('File', 'File'), ('Text', 'Text'), ('Boolean', 'Boolean')], default='Text', max_length=10)),
                ('question', models.CharField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comp.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
