# Generated by Django 3.1 on 2020-11-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_banner'),
        ('comp', '0006_auto_20201122_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('unreviewed', 'ureviewed'), ('under review', 'under review'), ('accepted', 'accepted'), ('changes required', 'changes required'), ('denied', 'denied')], default='unreviewed', max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='City',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.city'),
        ),
    ]
