# Generated by Django 3.1 on 2020-09-27 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('unreviewed', 'ureviewed'), ('under review', 'under review'), ('accepted', 'accepted'), ('pending', 'pending'), ('workinprogress', 'workinprogress'), ('denied', 'denied'), ('future-release', 'future-release')], default='unreviewed', max_length=25)),
                ('response_comment', models.TextField()),
                ('is_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='issuerep.issuetype')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
